version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=psql_admin
      - POSTGRES_PASSWORD=Bananen.123
      - POSTGRES_DB=db_chrischonaPlaner
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_URL=https://chrischona.heggli.dev
      - DATABASE_URL=postgresql://psql_admin:Bananen.123@db:5432/db_chrischonaPlaner_prod
      - NEXTAUTH_SECRET=secret
      - PORT=3000
    command: npm start  # Use 'npm start' for production

  migrate:  # New service for database migration
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://psql_admin:Bananen.123@db:5432/db_chrischonaPlaner_prod
    command: npx prisma migrate deploy

  seed:  # New service for database seeding
    build: .
    depends_on:
      - migrate  # Seed depends on the migration being completed
    environment:
      - DATABASE_URL=postgresql://psql_admin:Bananen.123@db:5432/db_chrischonaPlaner_prod
    command: npx prisma db seed

volumes:
  postgres_data: